<!DOCTYPE HTML>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>🇧🇷 Erros recuperáveis com Result - </title>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#ffffff" />

        <base href="">

        <link rel="stylesheet" href="book.css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:500" rel="stylesheet" type="text/css">

        <link rel="shortcut icon" href="favicon.png">

        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

        <link rel="stylesheet" href="highlight.css">
        <link rel="stylesheet" href="tomorrow-night.css">
        <link rel="stylesheet" href="ayu-highlight.css">

        <!-- Custom theme -->
        

        

        <!-- Fetch Clipboard.js from CDN but have a local fallback -->
        <script src="https://cdn.jsdelivr.net/clipboard.js/1.6.1/clipboard.min.js"></script>
        <script>
            if (typeof Clipboard == 'undefined') {
                document.write(unescape("%3Cscript src='clipboard.min.js'%3E%3C/script%3E"));
            }
        </script>

    </head>
    <body class="light">
        <!-- Work around some values being stored in localStorage wrapped in quotes -->
        <script type="text/javascript">
            try {
                var theme = localStorage.getItem('mdbook-theme');
                var sidebar = localStorage.getItem('mdbook-sidebar');

                if (theme.startsWith('"') && theme.endsWith('"')) {
                    localStorage.setItem('mdbook-theme', theme.slice(1, theme.length - 1));
                }

                if (sidebar.startsWith('"') && sidebar.endsWith('"')) {
                    localStorage.setItem('mdbook-sidebar', sidebar.slice(1, sidebar.length - 1));
                }
            } catch (e) { }
        </script>

        <!-- Set the theme before any content is loaded, prevents flash -->
        <script type="text/javascript">
            var theme;
            try { theme = localStorage.getItem('mdbook-theme'); } catch(e) { } 
            if (theme === null || theme === undefined) { theme = 'light'; }
            document.body.className = theme;
            document.querySelector('html').className = theme;
        </script>

        <!-- Hide / unhide sidebar before it is displayed -->
        <script type="text/javascript">
            var sidebar = 'hidden';
            if (document.body.clientWidth >= 1080) {
                try { sidebar = localStorage.getItem('mdbook-sidebar'); } catch(e) { }
                sidebar = sidebar || 'visible';
            }
            document.querySelector('html').classList.add("sidebar-" + sidebar);
        </script>

        <nav id="sidebar" class="sidebar" aria-label="Table of contents">
            <ol class="chapter"><li><a href="ch01-00-introduction.html"><strong aria-hidden="true">1.</strong> 🇧🇷 Introdução</a></li><li><ol class="section"><li><a href="ch01-01-installation.html"><strong aria-hidden="true">1.1.</strong> 🇧🇷 Instalação</a></li><li><a href="ch01-02-hello-world.html"><strong aria-hidden="true">1.2.</strong> 🇧🇷 Olá, Mundo!</a></li></ol></li><li><a href="ch02-00-guessing-game-tutorial.html"><strong aria-hidden="true">2.</strong> 🇧🇷 Jogo de Adivinhação</a></li><li><a href="ch03-00-common-programming-concepts.html"><strong aria-hidden="true">3.</strong> 🇧🇷 Conceitos Comuns de Programação</a></li><li><ol class="section"><li><a href="ch03-01-variables-and-mutability.html"><strong aria-hidden="true">3.1.</strong> 🇧🇷 Variáveis e Mutabilidade</a></li><li><a href="ch03-02-data-types.html"><strong aria-hidden="true">3.2.</strong> 🇧🇷 Tipos de dados</a></li><li><a href="ch03-03-how-functions-work.html"><strong aria-hidden="true">3.3.</strong> 🇧🇷 Funções</a></li><li><a href="ch03-04-comments.html"><strong aria-hidden="true">3.4.</strong> 🇧🇷 Comentários</a></li><li><a href="ch03-05-control-flow.html"><strong aria-hidden="true">3.5.</strong> 🇧🇷 Controle de fluxo</a></li></ol></li><li><a href="ch04-00-understanding-ownership.html"><strong aria-hidden="true">4.</strong> 🇧🇷 Entendendo Ownership</a></li><li><ol class="section"><li><a href="ch04-01-what-is-ownership.html"><strong aria-hidden="true">4.1.</strong> 🇧🇷 O Que É Ownership?</a></li><li><a href="ch04-02-references-and-borrowing.html"><strong aria-hidden="true">4.2.</strong> 🇧🇷 Referências e Borrowing</a></li><li><a href="ch04-03-slices.html"><strong aria-hidden="true">4.3.</strong> 🇧🇷 Slices</a></li></ol></li><li><a href="ch05-00-structs.html"><strong aria-hidden="true">5.</strong> 🇧🇷 Structs</a></li><li><ol class="section"><li><a href="ch05-01-method-syntax.html"><strong aria-hidden="true">5.1.</strong> Method Syntax</a></li></ol></li><li><a href="ch06-00-enums.html"><strong aria-hidden="true">6.</strong> 🇧🇷 Enums e Casamento de Padrões</a></li><li><ol class="section"><li><a href="ch06-01-defining-an-enum.html"><strong aria-hidden="true">6.1.</strong> 🇧🇷 Definindo uma Enum</a></li><li><a href="ch06-02-match.html"><strong aria-hidden="true">6.2.</strong> 🇧🇷 Operador match</a></li><li><a href="ch06-03-if-let.html"><strong aria-hidden="true">6.3.</strong> 🇧🇷 Controle de Fluxo Conciso com if let</a></li></ol></li><li><a href="ch07-00-modules.html"><strong aria-hidden="true">7.</strong> 🇧🇷 Módulos</a></li><li><ol class="section"><li><a href="ch07-01-mod-and-the-filesystem.html"><strong aria-hidden="true">7.1.</strong> 🇧🇷 mod e o Sistema de Arquivos</a></li><li><a href="ch07-02-controlling-visibility-with-pub.html"><strong aria-hidden="true">7.2.</strong> 🇧🇷 Controlando a Visibilidade com pub</a></li><li><a href="ch07-03-importing-names-with-use.html"><strong aria-hidden="true">7.3.</strong> 🇧🇷 Importando nomes com use</a></li></ol></li><li><a href="ch08-00-fundamental-collections.html"><strong aria-hidden="true">8.</strong> Fundamental Collections</a></li><li><ol class="section"><li><a href="ch08-01-vectors.html"><strong aria-hidden="true">8.1.</strong> 🇧🇷 Vetores</a></li><li><a href="ch08-02-strings.html"><strong aria-hidden="true">8.2.</strong> 🇧🇷 Strings</a></li><li><a href="ch08-03-hash-maps.html"><strong aria-hidden="true">8.3.</strong> 🇧🇷 Hash Maps</a></li></ol></li><li><a href="ch09-00-error-handling.html"><strong aria-hidden="true">9.</strong> 🇧🇷 Tratamento de Erros</a></li><li><ol class="section"><li><a href="ch09-01-unrecoverable-errors-with-panic.html"><strong aria-hidden="true">9.1.</strong> 🇧🇷 Erros Irrecuperáveis com panic!</a></li><li><a href="ch09-02-recoverable-errors-with-result.html" class="active"><strong aria-hidden="true">9.2.</strong> 🇧🇷 Erros recuperáveis com Result</a></li><li><a href="ch09-03-to-panic-or-not-to-panic.html"><strong aria-hidden="true">9.3.</strong> 🇧🇷 Entrar em panic! ou Não Entrar em panic!</a></li></ol></li><li><a href="ch10-00-generics.html"><strong aria-hidden="true">10.</strong> 🇧🇷 Tipos Genéricos, Traits, e Tempos de vida (Lifetimes)</a></li><li><ol class="section"><li><a href="ch10-01-syntax.html"><strong aria-hidden="true">10.1.</strong> 🇧🇷 Tipos Genéricos de Dados</a></li><li><a href="ch10-02-traits.html"><strong aria-hidden="true">10.2.</strong> 🇧🇷 Traits: Definindo Comportamento Compartilhado</a></li><li><a href="ch10-03-lifetime-syntax.html"><strong aria-hidden="true">10.3.</strong> 🇧🇷 Validating References with Lifetimes</a></li></ol></li><li><a href="ch11-00-testing.html"><strong aria-hidden="true">11.</strong> Testing</a></li><li><ol class="section"><li><a href="ch11-01-writing-tests.html"><strong aria-hidden="true">11.1.</strong> Writing tests</a></li><li><a href="ch11-02-running-tests.html"><strong aria-hidden="true">11.2.</strong> Running tests</a></li><li><a href="ch11-03-test-organization.html"><strong aria-hidden="true">11.3.</strong> Test Organization</a></li></ol></li><li><a href="ch12-00-an-io-project.html"><strong aria-hidden="true">12.</strong> An I/O Project</a></li><li><ol class="section"><li><a href="ch12-01-accepting-command-line-arguments.html"><strong aria-hidden="true">12.1.</strong> Accepting Command Line Arguments</a></li><li><a href="ch12-02-reading-a-file.html"><strong aria-hidden="true">12.2.</strong> Reading a File</a></li><li><a href="ch12-03-improving-error-handling-and-modularity.html"><strong aria-hidden="true">12.3.</strong> Improving Error Handling and Modularity</a></li><li><a href="ch12-04-testing-the-librarys-functionality.html"><strong aria-hidden="true">12.4.</strong> Testing the Library's Functionality</a></li><li><a href="ch12-05-working-with-environment-variables.html"><strong aria-hidden="true">12.5.</strong> Working with Environment Variables</a></li><li><a href="ch12-06-writing-to-stderr-instead-of-stdout.html"><strong aria-hidden="true">12.6.</strong> Writing to stderr instead of stdout</a></li></ol></li><li><a href="ch13-00-functional-features.html"><strong aria-hidden="true">13.</strong> Functional Language Features in Rust</a></li><li><ol class="section"><li><a href="ch13-01-closures.html"><strong aria-hidden="true">13.1.</strong> Closures</a></li><li><a href="ch13-02-iterators.html"><strong aria-hidden="true">13.2.</strong> Iterators</a></li><li><a href="ch13-03-improving-our-io-project.html"><strong aria-hidden="true">13.3.</strong> Improving our I/O Project</a></li><li><a href="ch13-04-performance.html"><strong aria-hidden="true">13.4.</strong> Performance</a></li></ol></li><li><a href="ch14-00-more-about-cargo.html"><strong aria-hidden="true">14.</strong> More about Cargo and Crates.io</a></li><li><ol class="section"><li><a href="ch14-01-release-profiles.html"><strong aria-hidden="true">14.1.</strong> Release Profiles</a></li><li><a href="ch14-02-publishing-to-crates-io.html"><strong aria-hidden="true">14.2.</strong> Publishing a Crate to Crates.io</a></li><li><a href="ch14-03-cargo-workspaces.html"><strong aria-hidden="true">14.3.</strong> Cargo Workspaces</a></li><li><a href="ch14-04-installing-binaries.html"><strong aria-hidden="true">14.4.</strong> Installing Binaries from Crates.io with cargo install</a></li><li><a href="ch14-05-extending-cargo.html"><strong aria-hidden="true">14.5.</strong> Extending Cargo with Custom Commands</a></li></ol></li><li><a href="ch15-00-smart-pointers.html"><strong aria-hidden="true">15.</strong> 🇧🇷 Ponteiros Inteligentes (Smart Pointers)</a></li><li><ol class="section"><li><a href="ch15-01-box.html"><strong aria-hidden="true">15.1.</strong> 🇧🇷 Box<T> Aponta para Dados no Heap e Tem Tamanho Conhecido</a></li><li><a href="ch15-02-deref.html"><strong aria-hidden="true">15.2.</strong> 🇧🇷 Tratando Ponteiros Inteligentes como Referências Normais com a Trait Deref</a></li><li><a href="ch15-03-drop.html"><strong aria-hidden="true">15.3.</strong> 🇧🇷 A Trait Drop Roda Código durante a Limpeza</a></li><li><a href="ch15-04-rc.html"><strong aria-hidden="true">15.4.</strong> 🇧🇷 Rc<T>, o Ponteiro Inteligente com Contagem de Referências</a></li><li><a href="ch15-05-interior-mutability.html"><strong aria-hidden="true">15.5.</strong> 🇧🇷 RefCell<T> e a Pattern de Mutabilidade Interior</a></li><li><a href="ch15-06-reference-cycles.html"><strong aria-hidden="true">15.6.</strong> 🇧🇷 Ciclos de Referências Podem Vazar Memória</a></li></ol></li><li><a href="ch16-00-concurrency.html"><strong aria-hidden="true">16.</strong> Concurrency</a></li><li><a href="ch17-00-oop.html"><strong aria-hidden="true">17.</strong> 🇧🇷 Rust é uma linguagem orientada a objetos?</a></li><li><ol class="section"><li><a href="ch17-01-what-is-oo.html"><strong aria-hidden="true">17.1.</strong> 🇧🇷 O que significa orientado a objetos?</a></li><li><a href="ch17-02-trait-objects.html"><strong aria-hidden="true">17.2.</strong> 🇧🇷 Usando objetos trait que permitem valores de tipos diferentes</a></li><li><a href="ch17-03-oo-design-patterns.html"><strong aria-hidden="true">17.3.</strong> 🇧🇷 Implementando um padrão de projeto orientado a objetos</a></li></ol></li><li><a href="ch18-00-patterns.html"><strong aria-hidden="true">18.</strong> Patterns</a></li><li><a href="ch19-00-more-lifetimes.html"><strong aria-hidden="true">19.</strong> More Lifetimes</a></li><li><a href="ch20-00-advanced-types.html"><strong aria-hidden="true">20.</strong> Advanced Type System Features</a></li><li><a href="appendix-00.html"><strong aria-hidden="true">21.</strong> Appendix</a></li><li><ol class="section"><li><a href="appendix-01-keywords.html"><strong aria-hidden="true">21.1.</strong> Keywords</a></li><li><a href="appendix-02-operators.html"><strong aria-hidden="true">21.2.</strong> Operators</a></li><li><a href="appendix-03-derivable-traits.html"><strong aria-hidden="true">21.3.</strong> Derivable Traits</a></li><li><a href="appendix-04-nightly-rust.html"><strong aria-hidden="true">21.4.</strong> Nightly Rust</a></li><li><a href="appendix-05-macros.html"><strong aria-hidden="true">21.5.</strong> Macros</a></li></ol></li></ol>
        </nav>

        <div id="page-wrapper" class="page-wrapper">

            <div class="page">
                
                <div id="menu-bar" class="menu-bar">
                    <div id="menu-bar-sticky-container">
                        <div class="left-buttons">
                            <button id="sidebar-toggle" class="icon-button" type="button" title="Toggle Table of Contents" aria-label="Toggle Table of Contents" aria-controls="sidebar">
                                <i class="fa fa-bars"></i>
                            </button>
                            <button id="theme-toggle" class="icon-button" type="button" title="Change theme" aria-label="Change theme" aria-haspopup="true" aria-expanded="false" aria-controls="theme-list">
                                <i class="fa fa-paint-brush"></i>
                            </button>
                            <ul id="theme-list" class="theme-popup" aria-label="submenu">
                                <li><button class="theme" id="light">Light <span class="default">(default)</span></button></li>
                                <li><button class="theme" id="rust">Rust</button></li>
                                <li><button class="theme" id="coal">Coal</button></li>
                                <li><button class="theme" id="navy">Navy</button></li>
                                <li><button class="theme" id="ayu">Ayu</button></li>
                            </ul>
                        </div>

                        <h1 class="menu-title"></h1>

                        <div class="right-buttons">
                            <a href="print.html" title="Print this book" aria-label="Print this book">
                                <i id="print-button" class="fa fa-print"></i>
                            </a>
                        </div>
                    </div>
                </div>

                <!-- Apply ARIA attributes after the sidebar and the sidebar toggle button are added to the DOM -->
                <script type="text/javascript">
                    document.getElementById('sidebar-toggle').setAttribute('aria-expanded', sidebar === 'visible');
                    document.getElementById('sidebar').setAttribute('aria-hidden', sidebar !== 'visible');
                    Array.from(document.querySelectorAll('#sidebar a')).forEach(function(link) {
                        link.setAttribute('tabIndex', sidebar === 'visible' ? 0 : -1);
                    });
                </script>

                <div id="content" class="content">
                    <main>
                        <a class="header" href="ch09-02-recoverable-errors-with-result.html#erros-recuperáveis-com-result" id="erros-recuperáveis-com-result"><h2>Erros recuperáveis com <code>Result</code></h2></a>
<p>A maior parte dos erros não são sérios o suficiente para precisar que o
programa pare totalmente. Às vezes, quando uma função falha, é por uma
razão que nós podemos facilmente interpretar e responder. Por exemplo,
se tentamos abrir um arquivo e essa operação falhar porque o arquivo não
existe, nós podemos querer criar o arquivo em vez de terminar o processo.</p>
<p>Lembre-se do Capítulo 2, na seção “<a href="ch02-00-guessing-game-tutorial.html#handling-potential-failure-with-the-result-type">Tratando Potenciais Falhas com o Tipo Result</a></p>
<!-- ignore -->”  que o enum `Result` é definido como tendo duas variantes,
`Ok` e `Err`, como mostrado a seguir:
<pre><pre class="playpen"><code class="language-rust">
# #![allow(unused_variables)]
#fn main() {
enum Result&lt;T, E&gt; {
    Ok(T),
    Err(E),
}
#}</code></pre></pre>
<p>O <code>T</code> e <code>E</code> são parâmetros de tipos genéricos: nós os discutiremos em mais
detalhe no Capítulo 10. O que você precisa saber agora é que <code>T</code> representa
o tipo do valor que vai ser retornado dentro da variante <code>Ok</code> em caso de sucesso,
e <code>E</code> representa o tipo de erro que será retornado dentro da variante <code>Err</code>
em caso de falha. Por <code>Result</code> ter esses parâmetros de tipo genéricos, nós
podemos usar o tipo <code>Result</code> e as funções que a biblioteca padrão definiu sobre
ele em diversas situações em que o valor de sucesso e o valor de erro que
queremos retornar possam divergir.</p>
<p>Vamos chamar uma função que retorna um valor <code>Result</code> porque a função poderia
falhar: na Listagem 9-3 tentamos abrir um arquivo:</p>
<p><span class="filename">Arquivo: src/main.rs</span></p>
<pre><pre class="playpen"><code class="language-rust">use std::fs::File;

fn main() {
    let f = File::open(&quot;hello.txt&quot;);
}
</code></pre></pre>
<p><span class="caption">Listagem 9-3: Abrindo um arquivo</span></p>
<p>Como sabemos que <code>File::open</code> retorna um <code>Result</code>? Poderíamos olhar na documentação
da API da biblioteca padrão, ou poderíamos perguntar para o compilador! Se damos à <code>f</code>
uma anotação de tipo que sabemos <em>não</em> ser o tipo retornado pela função e tentamos
compilar o código, o compilador nos dirá que os tipos não casam. A mensagem de erro
vai então nos dizer qual é, <em>de fato</em>, o tipo de <code>f</code>. Vamos tentar isso: nós sabemos que
o tipo retornado por <code>File::open</code> não é <code>u32</code>, então vamos mudar a declaração
<code>let f</code> para isso:</p>
<pre><code class="language-rust ignore">let f: u32 = File::open(&quot;hello.txt&quot;);
</code></pre>
<p>Tentar compilar agora nos dá a seguinte saída:</p>
<pre><code class="language-text">error[E0308]: mismatched types
 --&gt; src/main.rs:4:18
  |
4 |     let f: u32 = File::open(&quot;hello.txt&quot;);
  |                  ^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found enum
`std::result::Result`
  |
  = note: expected type `u32`
  = note:    found type `std::result::Result&lt;std::fs::File, std::io::Error&gt;`
</code></pre>
<p>Isso nos diz que o valor de retorno de <code>File::open</code> é um <code>Result&lt;T, E&gt;</code>.
O parâmetro genérico <code>T</code> foi preenchido aqui com o tipo do valor de sucesso,
<code>std::fs::File</code>, que é um <em>handle</em> de arquivo. O tipo de <code>E</code> usado no valor
de erro é <code>std::io::Error</code>.</p>
<p>Esse tipo de retorno significa que a chamada a <code>File::open</code> pode dar certo
e retornar para nós um <em>handle</em> de arquivo que podemos usar pra ler ou escrever
nele. Essa chamada de função pode também falhar: por exemplo, o arquivo pode não
existir ou talvez não tenhamos permissão para acessar o arquivo. A função <code>File::open</code>
precisa ter uma maneira de nos dizer se ela teve sucesso ou falhou e ao mesmo tempo
nos dar ou o <em>handle</em> de arquivo ou informação sobre o erro. Essa informação é
exatamente o que o enum <code>Result</code> comunica.</p>
<p>No caso em que <code>File::open</code> tem sucesso, o valor na variável <code>f</code> será uma instância
de <code>Ok</code> que contém um <em>handle</em> de arquivo. No caso em que ela falha, o valor em <code>f</code>
será uma instância de <code>Err</code> que contém mais informação sobre o tipo de erro que
aconteceu.</p>
<p>Devemos fazer com que o código na Listagem 9-3 faça diferentes ações dependendo
do valor retornado por <code>File::open</code>. A Listagem 9-4 mostra uma maneira de lidar
com o <code>Result</code> usando uma ferramenta básica: a expressão <code>match</code> que discutimos
no Capítulo 6.</p>
<p><span class="filename">Arquivo: src/main.rs</span></p>
<pre><pre class="playpen"><code class="language-rust should_panic">use std::fs::File;

fn main() {
    let f = File::open(&quot;hello.txt&quot;);

    let f = match f {
        Ok(file) =&gt; file,
        Err(error) =&gt; {
            panic!(&quot;Houve um problema ao abrir o arquivo: {:?}&quot;, error)
        },
    };
}
</code></pre></pre>
<p><span class="caption">Listagem 9-4: Usando uma expressão <code>match</code> para tratar as
variantes de <code>Result</code> que podemos encontrar.</span></p>
<p>Note que, como no enum <code>Option</code>, o enum <code>Result</code> e suas variantes foram importadas
no prelúdio, então não precisamos especificar <code>Result::</code> antes das variantes <code>Ok</code>
e <code>Err</code> nas linhas de <code>match</code>.</p>
<p>Aqui dizemos ao Rust que quando o resultado é <code>Ok</code> ele deve retornar o valor
interno <code>file</code> de dentro da variante <code>Ok</code> e nós então podemos atribuir este
valor de <em>handle</em> de arquivo à variável <code>f</code>. Depois do <code>match</code>, nós podemos então
usar o <em>handle</em> de arquivo para ler ou escrever.</p>
<p>A outra linha de <code>match</code> trata do caso em que recebemos um valor de <code>Err</code> de
<code>File::open</code>. Nesse exemplo, nós escolhemos chamar a macro <code>panic!</code>. Se não
há nenhum arquivo chamado <em>hello.txt</em> no diretório atual e rodarmos esse código,
veremos a seguinte saída da macro <code>panic!</code>:</p>
<pre><code class="language-text">thread 'main' panicked at 'Houve um problema ao abrir o arquivo: Error { repr:
Os { code: 2, message: &quot;No such file or directory&quot; } }', src/main.rs:9:12

</code></pre>
<p>Como sempre, essa saída nos diz exatamente o que aconteceu de errado.</p>
<a class="header" href="ch09-02-recoverable-errors-with-result.html#usando-match-com-diferentes-erros" id="usando-match-com-diferentes-erros"><h3>Usando <code>match</code> com Diferentes Erros</h3></a>
<p>O código na Listagem 9-4 chamará <code>panic!</code> não importa a razão pra <code>File::open</code>
ter falhado. O que queremos fazer em vez disso é tomar diferentes ações para diferentes
motivos de falha: se <code>File::open</code> falhou porque o arquivo não existe, nós
queremos criar um arquivo e retornar o <em>handle</em> para ele. Se <code>File::open</code>
falhou por qualquer outra razão, por exemplo porque não temos a permissão para
abrir o arquivo, nós ainda queremos chamar <code>panic!</code> da mesma maneira que fizemos
na Listagem 9-4. Veja a Listagem 9-5, que adiciona outra linha ao <code>match</code>:</p>
<p><span class="filename">Arquivo: src/main.rs</span></p>
<!-- ignore this test because otherwise it creates hello.txt which causes other
tests to fail lol -->
<pre><code class="language-rust ignore">use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open(&quot;hello.txt&quot;);

    let f = match f {
        Ok(file) =&gt; file,
        Err(ref error) if error.kind() == ErrorKind::NotFound =&gt; {
            match File::create(&quot;hello.txt&quot;) {
                Ok(fc) =&gt; fc,
                Err(e) =&gt; {
                    panic!(
                        &quot;Tentou criar um arquivo e houve um problema: {:?}&quot;,
                        e
                    )
                },
            }
        },
        Err(error) =&gt; {
            panic!(
                &quot;Houve um problema ao abrir o arquivo: {:?}&quot;,
                error
            )
        },
    };
}
</code></pre>
<p><span class="caption">Listagem 9-5: Tratando diferentes tipos de erros de diversas
maneiras.</span></p>
<p>O tipo do valor que <code>File::open</code> retorna dentro da variante <code>Err</code> é <code>io::Error</code>,
que é uma struct fornecida pela biblioteca padrão. Essa struct tem o método
<code>kind</code> que podemos chamar para receber um valor de <code>io::ErrorKind</code>. <code>io::ErrorKind</code>
é um enum fornecido pela biblioteca padrão que tem variantes representanto diversos
tipos de erros que podem ocorrer em uma operação de <code>io</code>. A variante que queremos
usar é <code>ErrorKind::NotFound</code>, que indica que o arquivo que queremos abrir não existe
ainda.</p>
<p>A condição <code>if error.kind() == ErrorKind::NotFound</code> é chamada de um <em>match guard</em>:
é uma condição extra dentro de uma linha de <code>match</code> que posteriormente refina
o padrão da linha. Essa condição deve ser verdadeira para o código da linha ser
executado; caso contrário a análise de padrões vai continuar considerando as
próximas linhas no <code>match</code>. O <code>ref</code> no padrão é necessário para que o <code>error</code>
não seja movido para a condição do <em>guard</em>, mas meramente referenciado por ele.
A razão de <code>ref</code> ser utilizado em vez de <code>&amp;</code> para pegar uma referência vai ser
discutida em detalhe no Capítulo 18. Resumindo, no contexto de um padrão, <code>&amp;</code>
corresponde a uma referência e nos dá seu valor, enquanto <code>ref</code> corresponde a um valor
e nos dá uma referência a ele.</p>
<p>A condição que queremos checar no <em>match guard</em> é se o valor retornado pelo
<code>error.kind()</code> é a variante <code>NotFound</code> do enum <code>ErrorKind</code>. Se é, queremos
tentar criar um arquivo com <code>File::create</code>. No entanto, como <code>File::create</code>
pode também falhar, precisamos adicionar um <code>match</code> interno também. Quando
o arquivo não pode ser aberto, outro tipo de mensagem de erro será mostrada.
A última linha do <code>match</code> externo continua a mesma de forma que o programa
entre em pânico pra qualquer erro além do de arquivo ausente.</p>
<a class="header" href="ch09-02-recoverable-errors-with-result.html#atalhos-para-pânico-em-erro-unwrap-e-expect" id="atalhos-para-pânico-em-erro-unwrap-e-expect"><h3>Atalhos para Pânico em Erro: <code>unwrap</code> e <code>expect</code></h3></a>
<p>Usar <code>match</code> funciona bem o suficiente, mas pode ser um pouco verboso e nem
sempre comunica tão bem a intenção. O tipo <code>Result&lt;T, E&gt;</code> tem vários métodos
auxiliares definidos para fazer diversas tarefas. Um desses métodos, chamado
<code>unwrap</code>, é um método de atalho que é implementado justamente como o <code>match</code> que
escrevemos na Listagem 9-4. Se o valor de <code>Result</code> for da variante <code>Ok</code>, <code>unwrap</code>
vai retornar o valor dentro de <code>Ok</code>. Se o <code>Result</code> for da variante <code>Err</code>, <code>unwrap</code>
vai chamar a macro <code>panic!</code>. Aqui um exemplo de <code>unwrap</code> em ação:</p>
<p><span class="filename">Arquivo: src/main.rs</span></p>
<pre><pre class="playpen"><code class="language-rust should_panic">use std::fs::File;

fn main() {
    let f = File::open(&quot;hello.txt&quot;).unwrap();
}
</code></pre></pre>
<p>Se rodarmos esse código sem um arquivo <em>hello.txt</em>, veremos uma mensagem de erro
da chamada de <code>panic!</code> que o método <code>unwrap</code> faz:</p>
<pre><code class="language-text">thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error {
repr: Os { code: 2, message: &quot;No such file or directory&quot; } }',
/stable-dist-rustc/build/src/libcore/result.rs:868
</code></pre>
<p>Outro método, <code>expect</code>, que é semelhante a <code>unwrap</code>, nos deixa também escolher
a mensagem de erro do <code>panic!</code>. Usar <code>expect</code> em vez de <code>unwrap</code> e fornecer
boas mensagens de erros podem transmitir sua intenção e tornar a procura pela
fonte de pânico mais fácil. A sintaxe de <code>expect</code> é a seguinte:</p>
<p><span class="filename">Arquivo: src/main.rs</span></p>
<pre><pre class="playpen"><code class="language-rust should_panic">use std::fs::File;

fn main() {
    let f = File::open(&quot;hello.txt&quot;).expect(&quot;Falhou ao abrir hello.txt&quot;);
}
</code></pre></pre>
<p>Nós usamos <code>expect</code> da mesma maneira que <code>unwrap</code>: para retornar o <em>handle</em> de arquivo
ou chamar a macro de <code>panic!</code>. A mensagem de erro usada por <code>expect</code> na sua chamada
de <code>panic!</code> será o parâmtero que passamos para <code>expect</code> em vez da mensagem padrão
que o <code>unwrap</code> usa. Aqui está como ela aparece:</p>
<pre><code class="language-text">thread 'main' panicked at 'Falhou ao abrir hello.txt: Error { repr: Os { code:
2, message: &quot;No such file or directory&quot; } }',
/stable-dist-rustc/build/src/libcore/result.rs:868
</code></pre>
<p>Como essa mensagem de erro começa com o texto que especificamos, <code>Falhou ao abrir hello.txt</code>, será mais fácil encontrar o trecho do código de onde vem essa mensagem de erro. Se usamos <code>unwrap</code> em diversos lugares, pode tomar mais tempo encontrar
exatamente qual dos <code>unwrap</code> está causando o pânico, dado que todas as chamadas
a <code>unwrap</code> chamam o print de pânico com a mesma mensagem.</p>
<a class="header" href="ch09-02-recoverable-errors-with-result.html#propagando-erros" id="propagando-erros"><h3>Propagando Erros</h3></a>
<p>Quando você está escrevendo uma função cuja implementação chama algo que pode
falhar, em vez de tratar o erro dentro dessa função, você pode retornar o
erro ao código que a chamou de forma que ele possa decidir o que fazer. Isso é
conhecido como <em>propagar</em> o erro e dá mais controle ao código que chamou sua
função, onde talvez haja mais informação sobre como tratar o erro
do que você tem disponível no contexto do seu código.</p>
<p>Por exemplo, a Listagem 9-6 mostra uma função que lê um nome de usuário de um arquivo.
Se o arquivo não existe ou não pode ser lido, essa função vai retornar esses erros
ao código que chamou essa função:</p>
<p><span class="filename">Arquivo: src/main.rs</span></p>
<pre><pre class="playpen"><code class="language-rust">
# #![allow(unused_variables)]
#fn main() {
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {
    let f = File::open(&quot;hello.txt&quot;);

    let mut f = match f {
        Ok(file) =&gt; file,
        Err(e) =&gt; return Err(e),
    };

    let mut s = String::new();

    match f.read_to_string(&amp;mut s) {
        Ok(_) =&gt; Ok(s),
        Err(e) =&gt; Err(e),
    }
}
#}</code></pre></pre>
<p><span class="caption">Listagem 9-6: Uma função que retorna erros ao código que a chamou
usando <code>match</code></span></p>
<p>Vamos olhar primeiro ao tipo retornado pela função: <code>Result&lt;String, io::Error&gt;</code>.
Isso significa que a função está retornando um valor do tipo <code>Result&lt;T, E&gt;</code> onde
o parâmetro genérico <code>T</code> foi preenchido pelo tipo concreto <code>String</code> e o tipo genérico
<code>E</code> foi preenchido pelo tipo concreto <code>io::Error</code>. Se essa função tem sucesso sem
nenhum problema, o código que chama essa função vai receber um valor <code>Ok</code> que contém
uma <code>String</code>- o nome de usuário que essa função leu do arquivo. Se essa função
encontra qualquer problema, o código que a chama receberá um valor de <code>Err</code>
que contém uma instância de <code>io::Error</code>, que contém mais informação
sobre o que foi o problema. Escolhemos <code>io::Error</code> como o tipo de retorno
dessa função porque é este o tipo de erro retornado pelas
duas operações que estamos chamando no corpo dessa função que podem falhar:
a função <code>File::open</code> e o método <code>read_to_string</code>.</p>
<p>O corpo da função começa chamando a função <code>File::open</code>. Nós então tratamos
o valor de <code>Result</code> retornado usando um <code>match</code> semelhante ao da Listagem 9-4,
só que em vez de chamar <code>panic!</code> no caso de <code>Err</code>, retornamos mais cedo dessa função
e passamos o valor de erro de <code>File::open</code> de volta ao código que a chamou, como o
valor de erro da nossa função. Se <code>File::open</code> tem sucesso, nós guardamos o <em>handle</em> de
arquivo na variável <code>f</code> e continuamos.</p>
<p>Então, criamos uma nova <code>String</code> na variável <code>s</code> e chamamos o método <code>read_to_string</code>
no <em>handle</em> de arquivo <code>f</code> para ler o conteúdo do arquivo e armazená-lo em <code>s</code>. O método
<code>read_to_string</code> também retorna um <code>Result</code> porque ele pode falhar, mesmo que
<code>File::open</code> teve sucesso. Então precisamos de outro <code>match</code> para tratar esse
<code>Result</code>: se <code>read_to_string</code> teve sucesso, então nossa função teve sucesso, e nós
retornamos o nome de usuário lido do arquivo que está agora em <code>s</code>, encapsulado em um <code>Ok</code>.
Se <code>read_to_string</code> falhou, retornamos o valor de erro da mesma maneira que retornamos
o valor de erro no <code>match</code> que tratou o valor de retorno de <code>File::open</code>.
No entanto, não precisamos explicitamente escrever <code>return</code>, porque essa já é a
última expressão na função.</p>
<p>O código que chama nossa função vai então receber ou um valor <code>Ok</code> que
contém um nome de usuário ou um valor de <code>Err</code> que contém um <code>io::Error</code>. Nós
não sabemos o que o código que chamou nossa função fará com esses valores. Se o
código que chamou recebe um valor de <code>Err</code>, ele poderia chamar <code>panic!</code> e causar
um crash, usar um nome de usuário padrão, ou procurar o nome de usuário em outro
lugar que não um arquivo, por exemplo. Nós não temos informação o suficiente sobre
o que o código que chamou está de fato tentando fazer, então propagamos toda a
informação de sucesso ou erro para cima para que ele a trate apropriadamente.</p>
<p>Esse padrão de propagação de erros é tão comum em Rust que a linguagem disponibiliza
o operador de interrogação <code>?</code> para tornar isso mais fácil.</p>
<a class="header" href="ch09-02-recoverable-errors-with-result.html#um-atalho-para-propagar-erros-" id="um-atalho-para-propagar-erros-"><h4>Um Atalho Para Propagar Erros: <code>?</code></h4></a>
<p>A Listagem 9-7 mostra uma implementação de <code>read_username_from_file</code> que tem a
mesma funcionalidade que tinha na Listagem 9-6, mas esta implementação usa o operador
de interrogação:</p>
<p><span class="filename">Arquivo: src/main.rs</span></p>
<pre><pre class="playpen"><code class="language-rust">
# #![allow(unused_variables)]
#fn main() {
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {
    let mut f = File::open(&quot;hello.txt&quot;)?;
    let mut s = String::new();
    f.read_to_string(&amp;mut s)?;
    Ok(s)
}
#}</code></pre></pre>
<p><span class="caption">Listagem 9-7: Uma função que retorna erros para o código
que a chamou usando <code>?</code>.</span></p>
<p>O <code>?</code> colocado após um valor de <code>Result</code> é definido para funcionar quase
da mesma maneira que as expressões <code>match</code> que definimos para tratar o valor
de <code>Result</code> na Listagem 9-6. Se o valor de <code>Result</code> é um <code>Ok</code>, o valor dentro dele
vai ser retornado dessa expressão e o programa vai continuar. Se o valor
é um <code>Err</code>, o valor dentro dele vai ser retornado da função inteira como se
tivéssemos usado a palavra-chave <code>return</code> de modo que o valor de erro é propagado
ao código que chamou a função.</p>
<p>A única diferença entre a expressão <code>match</code> da Listagem 9-6 e o que o operador
de interrogação faz é que quando usamos o operador de interrogação, os valores
de erro passam pela função <code>from</code> definida no <em>trait</em> <code>From</code> na biblioteca
padrão. Vários tipos de erro implementam a função <code>from</code> para converter um
erro de um tipo em outro. Quando usado pelo operador de
interrogação, a chamada à função <code>from</code> converte o tipo de erro que o
operador recebe no tipo de erro definido no tipo de retorno da função em
que estamos usando <code>?</code>. Isso é útil quando partes de uma função podem falhar
por várias razões diferentes, mas a função retorna um tipo de erro que
representa todas as maneiras que a função pode falhar. Enquanto cada
tipo de erro implementar a função <code>from</code> para definir como se converter
ao tipo de erro retornado, o operador de interrogação lida com a conversão
automaticamente.</p>
<p>No contexto da Listagem 9-7, o <code>?</code> no final da chamada de <code>File::open</code> vai
retornar o valor dentro do <code>Ok</code> à variável <code>f</code>. Se um erro ocorrer, <code>?</code>
vai retornar mais cedo a função inteira e dar um valor de <code>Err</code> ao código
que a chamou. O mesmo se aplica ao <code>?</code> ao final da chamada de <code>read_to_string</code>.</p>
<p>O <code>?</code> elimina um monte de excesso e torna a implementação dessa
função mais simples. Poderíamos até encurtar ainda mais esse código
ao encadear chamadas de método imediatamente depois do <code>?</code>, como mostrado
na Listagem 9-8:</p>
<p><span class="filename">Arquivo: src/main.rs</span></p>
<pre><pre class="playpen"><code class="language-rust">
# #![allow(unused_variables)]
#fn main() {
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {
    let mut s = String::new();

    File::open(&quot;hello.txt&quot;)?.read_to_string(&amp;mut s)?;

    Ok(s)
}
#}</code></pre></pre>
<p><span class="caption">Listagem 9-8: Encadeando chamadas de método após o operador
de interrogação.</span></p>
<p>Nós movemos a criação da nova <code>String</code> em <code>s</code> para o começo da função;
essa parte não mudou. Em vez de criar uma variável <code>f</code>, nós encadeamos
a chamada para <code>read_to_string</code> diretamente ao resultado de
<code>File::open(&quot;hello.txt&quot;)?</code>. Nós ainda temos um <code>?</code> ao fim da chamada a
<code>read_to_string</code>, e ainda retornamos um valor de <code>Ok</code> contendo o nome de usuário
em <code>s</code> quando ambos os métodos <code>File::open</code> e <code>read_to_string</code> tiveram sucesso ao invés
de retornarem erros. Essa funcionalidade é novamente a mesma da Listagem 9-6 e
Listagem 9-7; essa é só uma maneira diferente e mais ergonômica de escrevê-la.</p>
<a class="header" href="ch09-02-recoverable-errors-with-result.html#-somente-pode-ser-usado-em-funções-que-retornam-result" id="-somente-pode-ser-usado-em-funções-que-retornam-result"><h4><code>?</code> Somente Pode Ser Usado em Funções Que Retornam Result</h4></a>
<p>O <code>?</code> só pode ser usado em funções que tem um tipo de retorno de <code>Result</code>,
porque está definido a funcionar da mesma maneira que a expressão <code>match</code> que
definimos na Listagem 9-6. A parte do <code>match</code> que requer um tipo de retorno de
<code>Result</code> é <code>return Err(e)</code>, então o tipo de retorno da função deve ser
um <code>Result</code> para ser compatível com esse <code>return</code>.</p>
<p>Vamos ver o que ocorre quando usamos <code>?</code> na função <code>main</code>, que como vimos, tem
um tipo de retorno de <code>()</code>:</p>
<pre><code class="language-rust ignore">use std::fs::File;

fn main() {
    let f = File::open(&quot;hello.txt&quot;)?;
}
</code></pre>
<p>Quando compilamos esse código recebemos a seguinte mensagem de erro:</p>
<pre><code class="language-text">error[E0277]: the `?` operator can only be used in a function that returns
`Result` (or another type that implements `std::ops::Try`)
 --&gt; src/main.rs:4:13
  |
4 |     let f = File::open(&quot;hello.txt&quot;)?;
  |             ------------------------
  |             |
  |             cannot use the `?` operator in a function that returns `()`
  |             in this macro invocation
  |
  = help: the trait `std::ops::Try` is not implemented for `()`
  = note: required by `std::ops::Try::from_error`
</code></pre>
<p>Esse erro aponta que só podemos usar o operador de interrogação em funções
que retornam <code>Result</code>. Em funções que não retornam <code>Result</code>, quando você chama
outras funções que retornam <code>Result</code>, você deve usar um <code>match</code> ou um dos métodos
de <code>Result</code> para tratá-lo em vez de usar <code>?</code> para potencialmente
propagar o erro ao código que a chamou.</p>
<p>Agora que discutimos os detalhes de chamar <code>panic!</code> ou retornar <code>Result</code>, vamos
retornar ao tópico de como decidir qual é apropriado para utilizar em quais
casos.</p>

                    </main>

                    <nav class="nav-wrapper" aria-label="Page navigation">
                        <!-- Mobile navigation buttons -->
                        
                            <a rel="prev" href="ch09-01-unrecoverable-errors-with-panic.html" class="mobile-nav-chapters previous" title="Previous chapter" aria-label="Previous chapter" aria-keyshortcuts="Left">
                                <i class="fa fa-angle-left"></i>
                            </a>
                        

                        
                            <a rel="next" href="ch09-03-to-panic-or-not-to-panic.html" class="mobile-nav-chapters next" title="Next chapter" aria-label="Next chapter" aria-keyshortcuts="Right">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        

                        <div style="clear: both"></div>
                    </nav>
                </div>
            </div>

            <nav class="nav-wide-wrapper" aria-label="Page navigation">
                
                    <a href="ch09-01-unrecoverable-errors-with-panic.html" class="nav-chapters previous" title="Previous chapter" aria-label="Previous chapter" aria-keyshortcuts="Left">
                        <i class="fa fa-angle-left"></i>
                    </a>
                

                
                    <a href="ch09-03-to-panic-or-not-to-panic.html" class="nav-chapters next" title="Next chapter" aria-label="Next chapter" aria-keyshortcuts="Right">
                        <i class="fa fa-angle-right"></i>
                    </a>
                
            </nav>

        </div>


        <!-- Local fallback for Font Awesome -->
        <script>
            if (getComputedStyle(document.querySelector(".fa")).fontFamily !== "FontAwesome") {
                var link = document.createElement('link');
                link.rel = 'stylesheet';
                link.type = 'text/css';
                link.href = '_FontAwesome/css/font-awesome.css';
                document.head.insertBefore(link, document.head.firstChild)
            }
        </script>

        

        

        

        

        <script src="highlight.js"></script>
        <script src="book.js"></script>

        <!-- Custom JS script -->
        

    </body>
</html>
